config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  root to: "home#index"
  #get 'home/index'

  resources :home do 
    collection do
      get 'index'
      get 'leave_configuration' 
      get 'all_users'
      get 'add_employee'
      get 'employee_list'
      get 'assets/:id' => 'assets#add_assets_info', as: :add_assets
      put 'assets/:id' => 'assets#update'    
      delete 'assets/:id' => 'assets#destroy'
      post 'create_assets' => 'assets#create_assets'  
      
    end
  end

  get 'edit_user/:id' =>'users#edit_user', as: :edit_user
  put 'update_user' => 'users#update_user'    
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :assets
  has_one :leave_summery
  has_one :user_profile
  has_many :leaves
  belongs_to :role
  belongs_to :manager, class_name: 'User', optional: true
  has_many :members, class_name: 'User', foreign_key: 'manager_id'

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    if user
      return user
    else
      registered_user = User.where(:email => access_token.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(provider:access_token.provider,
          email: data["email"],
          uid: access_token.uid ,
          password: Devise.friendly_token[0,20],
          role_id: 2
        )
      end
    end  
  end


  def is_user?
    self.role.code.eql?'user'
  end

  def is_line_manager?
    self.role.code.eql?'linemanager'
  end

  def is_admin?
    self.role.code.eql?'admin'  
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #load_and_authorize_resource
  def index
    
  end

  def edit_user
    #debugger
    @user = User.find(params[:id])
    if current_user.user_profile.present?
      @profile = current_user.user_profile
    else
      #authorize! :read, @user 
      @profile = current_user.build_user_profile
    end
  end

  def show
  end

  def update_user
    Date.parse(user_params[:join_date]) if user_params[:join_date].present?
    Date.parse(user_params[:dob]) if user_params[:dob].present?
    if current_user.user_profile.present?
      profile = current_user.user_profile
    else
      profile = current_user.build_user_profile
    end
    profile.update(user_params)
    flash[:notice] = "Updated Successfully"  
    redirect_to edit_user_path(current_user.id)
    #@user.user_profile.update(user_params)
  end

   private
    def user_params
      params.require(:user_profile).permit(:first_name, :last_name, :address, :city, :designation, :dob, :gender, :employee_code, :join_date, :maratial_status, :mobile_number
  )
    end

 
 end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/edit_user.html.erb
  <div class="wrapper">
    <div class="container">
      <div class="row">
        <div class="span3">
           <%= render "/layouts/sidebar" %>
        </div><!--/.span3-->


        <div class="span9">
          <div class="content">

            <div class="module">
              <div class="module-head">
                <h3> Edit User </h3>
              </div>
          
              <div class="module-body"> 
<!--   <p>Visible only for superadmins and supervisors! </p> -->
          
          <%= form_for [@user, @profile], url: update_user_path, method: 'put', class: "form-horizontal row-fluid" do |form| %>
                  <div class="control-group">
                    <div class="controls row-fluid">                  
                      <%= form.label :first_name, class: 'control-label' %>
                      <%= form.text_field :first_name, class: 'span8' %>
                     </div>
                   </div>                 
                  <div class="control-group">
                    <div class="controls row-fluid">
                      <%= form.label :last_name, class: 'control-label' %>
                      <%= form.text_field :last_name, class: 'span8' %>
                    </div>
                   </div>
                  <div class="control-group">
                    <div class="controls row-fluid">
                      <%= form.label :address, class: 'control-label' %>
                      <%= form.text_area :address, class: 'span8' %>
                    </div>
                   </div>
                   
                   <div class="control-group">
                    <div class="controls row-fluid">
                      <%= form.label :city, class: 'control-label'%>
                      <%= form.text_field :city, class: 'span4'%>
                    </div>
                   </div>
                    <div class="control-group">
                    <div class="controls row-fluid">
                      <%= form.label :designation, class: 'control-label'  %>
                      <%= form.text_field :designation, class: 'span8' %>
                    </div>
                   </div>
                    <div class="control-group">
                    <div class="controls row-fluid">
                      <%= form.label :dob, class: 'control-label' %>
                      <%= form.text_field :dob, class: 'datepicker' %>
                    </div>
                   </div>
                    <div class="control-group">
                    <div class="controls row-fluid">
                      <%= form.label :gender, class: 'control-label' %>
                      <%= form.radio_button :gender, 'male' %>male<br />
                      <%= form.radio_button :gender, 'female' %>female<br />
   
                   </div>
                   </div>
                    <div class="control-group">
                    <div class="controls row-fluid">
                      <%= form.label :employee_code, class: 'control-label' %>
                      <%= form.text_field :employee_code, class: 'span4' %>
                    </div>
                   </div>
                    <div class="control-group">
                    <div class="controls row-fluid">
                      <%= form.label :joining_date, class: 'control-label' %>
                      <%= form.text_field :join_date, class: 'datepicker' %>
                    </div>
                   </div>

                    <div class="control-group">
                    <div class="controls row-fluid">
                      <%= form.label :maratial_status, class: 'control-label' %>
                      <%= form.radio_button :maratial_status, 'married' %>married<br/>
                      <%= form.radio_button :maratial_status, 'unmarried' %>unmarried<br/>
                    </div>
                   </div>

                    <div class="control-group">
                    <div class="controls row-fluid">
                      <%= form.label :mobile_number, class: 'control-label' %>
                      <%= form.text_field :mobile_number, class: 'span8', required: true %>
                    </div>
                   </div>
<!--                       <%= form.submit %>
 -->                   <div class="control-group">
                      <div class="controls">
                        <button type="submit" class="btn btn-primary">Update profile</button>
                      </div>
                    </div>

                  <% end %>
                </form>
              </div>
            </div><!--/.module-->
          </div><!--/.content-->
        </div><!--/.span9-->
      </div>
    </div><!--/.container-->
  </div><!--/.wrapper-->

<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker();
  });
</script>