config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  root to: "home#index"
  #get 'home/index'

  resources :home do 
    collection do
      get 'index'
      get 'leave_configuration' 
      get 'all_users'
      get 'add_employee'
      get 'employee_list'
      get 'assets/:id' => 'assets#add_assets_info', as: :add_assets
      put 'assets/:id' => 'assets#update'    
      delete 'assets/:id' => 'assets#destroy'
      post 'create_assets' => 'assets#create_assets'  
      
    end
  end

  get 'edit_user/:id' =>'users#edit_user', as: :edit_user
  put 'update_user' => 'users#update_user'    
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #respond_to :html, :json
  def index
    
  end

  def new
  end

  def show
  end

  def leave_configuration
    if current_user.user_profile.present?
      @leave_configs = LeaveConfiguration.all
    else
      authorize! :read, @user
    end
  end

  def add_employee
  end

  def all_users
    if current_user.user_profile.present?
      @users = User.all
    else
      authorize! :read, @user
    end
  end

  def update
    #binding.pry
    #authorize! :read, @leave_configs
    #authorize! :read, @users
    #@roles = Role.all
    if params[:id] == 'all_users'
      
      if params[:email].present?
        @email1 = User.select(:email).map(&:email)[user_params["email"].to_i-1]
        mgr_user = User.find_for_authentication(:email => @email1)
        mgrid = mgr_user.id
        email2 = params[:email] 
        update_user = User.find_for_authentication(:email => email2)
        update_user.update(manager_id: mgr_user.id)


      elsif params[:user_id].present?       
        user = User.find(params[:user_id])
        user.update(user_params)
        redirect_to all_users_home_index_path(current_user.id)
      end

    elsif params[:id] == 'leave_configuration'

      LeaveConfiguration.update(leave_config_params)  
      redirect_to leave_configuration_home_index_path(current_user.id)
      
    end
  end

  def role  
  end

  def employee_list
  end

  private
    def leave_config_params
      params.require(:leave_configuration).permit(:sick_leaves, :privilege_leaves, :work_from_home, :casual_leaves)
    end

    def user_params
      params.require(:user).permit(:email, :role_id, :manager_id)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/add_employee.html.erb
  <div class="wrapper">
    <div class="container">
      <div class="row">
        <div class="span3">
           <%= render "/layouts/sidebar" %>
        </div><!--/.span3-->


        <div class="span9">
          <div class="content">

            <div class="module">
              <div class="module-head">
                <h3>Add Employee</h3>
              </div>
            





            
            </div><!--/.module-->

            <br />

          </div><!--/.content-->
        </div><!--/.span9-->
      </div>
    </div><!--/.container-->
  </div><!--/.wrapper-->

app/views/home/all_users.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="span3">
        <%= render "/layouts/sidebar" %>
      </div>
      <!--/.span3-->
      <div class="span9">
        <div class="content">
          <div class="module">
            <div class="module-head">
              <h3>User</h3>
            </div>
            <div class="module-body table">
              <table cellpadding="0" cellspacing="0" border="0" class="table table-bordered table-striped  display"" width="100%">
                <thead>
                <% if can? :update, @user%>

                  <tr>
                    <th>email id</th>
                    <th>role</th>
                    <th>change manager</th> 
                    <th>manager id</th>
                  </tr>
                </thead>
                <tbody>
                  <%@users.each do |user|%>
                  <tr class="odd gradeX">
                    <td><%=best_in_place user, :email, as: :input,url: all_users_home_index_path(user_id: user.id)%>
                    <td><%= best_in_place user, :role_id, as: :select, :collection => {"1" => "Admin", "2" => "User", "3" => "Line Manager"}, url: all_users_home_index_path(user_id: user.id)%>
                      <%#@users.each do |user|%>
                    <td><%= best_in_place user, :email, as: :select, :collection => User.select(:email).map(&:email) , url: all_users_home_index_path(email: user.email)%>
                    
                    <td><%=user.email%>
                      <%#end%>                     
                      <%#end%>                     
                  </tr>
                  <%end%>
                </tbody>
              </table>
              <%end%>
            </div>
          </div>
          <!--/.module-->
          <br />
        </div>
        <!--/.content-->
      </div>
      <!--/.span9-->
    </div>
  </div>
  <!--/.container-->
</div>
<!--/.wrapper-->

app/views/home/employee_list.html.erb
  <div class="wrapper">
    <div class="container">
      <div class="row">
        <div class="span3">
           <%= render "/layouts/sidebar" %>
        </div><!--/.span3-->


        <div class="span9">
          <div class="content">

            <div class="module">
              <div class="module-head">
                <h3>Employee List</h3>
              </div>
            





            
            </div><!--/.module-->

            <br />

          </div><!--/.content-->
        </div><!--/.span9-->
      </div>
    </div><!--/.container-->
  </div><!--/.wrapper-->

app/views/home/index.html.erb
  <div class="wrapper">
    <div class="container">
      <div class="row">
        <div class="span3">
           <%= render "/layouts/sidebar" %>
        </div><!--/.span3-->


        <div class="span9">
          <div class="content">

            <div class="module">
              <div class="module-head">
                <h3> </h3>
              </div>
              <div class="alert">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>Warning!</strong> make sure that you have filled your profile
                  </div>            





            
            </div><!--/.module-->

            <br />

          </div><!--/.content-->
        </div><!--/.span9-->
      </div>
    </div><!--/.container-->
  </div><!--/.wrapper-->

app/views/home/leave_configuration.html.erb
  <div class="wrapper">
    <div class="container">
      <div class="row">
        <div class="span3">
           <%= render "/layouts/sidebar" %>
        </div><!--/.span3-->

        <div class="span9">
          <div class="content">

            <div class="module">
              <div class="module-head">
                <h3>Leave Configuration</h3>
              </div>
               
              

              
                <div class="module-body table">
                <span >

                <table cellpadding="0" cellspacing="0" border="0" class="table table-bordered table-striped  display" width="100%">
                  <thead>
                    <tr>
                      <th>Sick Leaves</th>
                      <th>Privilage Leaves</th>
                      <th>Work From home</th>
                      <th>Casual Leaves</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr class="odd gradeX">
                      <%@leave_configs.each do |leave|%>

                        <td><%=best_in_place leave, :sick_leaves, as: :input, url: leave_configuration_home_index_path%>

                        </td>
                        <td><%=best_in_place leave, :privilege_leaves, as: :input, url: leave_configuration_home_index_path%>
                        </td>  
                        <td><%=best_in_place leave, :work_from_home, as: :input, url: leave_configuration_home_index_path%>
                        </td>
                        <td><%=best_in_place leave, :casual_leaves, as: :input, url: leave_configuration_home_index_path%>
                        </td>
                        <%end%>
                    </tr>
                   
                   </tbody>
                </table>
</span>
<br>


              </div>
            </div><!--/.module-->

            <br />

          </div><!--/.content-->
        </div><!--/.span9-->
      </div>
    </div><!--/.container-->
  </div><!--/.wrapper-->

app/views/home/user.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="span3">
        <%= render "/layouts/sidebar" %>
      </div>
      <!--/.span3-->
      <div class="span9">
        <div class="content">
          <div class="module">
            <div class="module-head">
              <h3>User</h3>
            </div>
            <div class="module-body table">
              <table cellpadding="0" cellspacing="0" border="0" class="table table-bordered table-striped  display"" width="100%">
                <thead>
                  <tr>
                    <th>email id</th>
                    <th>role</th>
                    <!-- <th>manager</th>  -->
                    <th>manager</th>
                  </tr>
                </thead>
                <tbody>
                  <%@users.each do |user|%>
                  <tr class="odd gradeX">
                    <td><%=best_in_place user, :email, as: :input,url: user_home_index_path(user_id: user.id)%>
                    <td><%= best_in_place user, :role_id, as: :select, :collection => {"1" => "Admin", "2" => "User", "3" => "Line Manager"}, url: user_home_index_path(user_id: user.id)%>
                      <%#@users.each do |user|%>
                      <td><%= select_tag 'manager', options_from_collection_for_select(@users, "id", "email"), prompt: "-Select Manager-"%></td>
                      <%#end%>                     
                      <%#end%>                     
                  </tr>
                  <%end%>
                </tbody>
              </table>
            </div>
          </div>
          <!--/.module-->
          <br />
        </div>
        <!--/.content-->
      </div>
      <!--/.span9-->
    </div>
  </div>
  <!--/.container-->
</div>
<!--/.wrapper-->