config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  root to: "home#index"
  #get 'home/index'

  resources :home do 
    collection do
      get 'index'
      get 'leave_configuration' 
      get 'all_users'
      get 'add_employee'
      get 'employee_list'
      get 'assets/:id' => 'assets#add_assets_info', as: :add_assets
      put 'assets/:id' => 'assets#update'    
      delete 'assets/:id' => 'assets#destroy'
      post 'create_assets' => 'assets#create_assets'  
      
    end
  end

  get 'edit_user/:id' =>'users#edit_user', as: :edit_user
  put 'update_user' => 'users#update_user'    
  
end

app/views/layouts/_footer.html.erb
    <div class="m-footer">
      <div class="container">
        <b class="copyright">&copy; 2018 Kumolus - kumolus.com </b>All rights reserved.
      </div>
    </div>
<!--   </body> -->

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
          <i class="icon-reorder shaded"></i></a>

          <a class="brand" href="http://localhost:3000/home/index">
              <img src="/assets/logo.jpg" width="40" height="40" class="d-inline-block align-top" alt="">

            Kumolus
          </a>
            <ul class="nav pull-right">
              
              <li class="nav-user dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <img src="/assets/user.png" class="nav-avatar" />
                <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Your Profile</a></li>
                  <li><a href="#">Account Settings</a></li>
                  <li><%= link_to('Edit Profile', edit_user_path(id:current_user.id) ) %></li>
                  <li class="divider"></li>
                  <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
                </ul>
              </li>
            </ul>
          </div>
          <!-- /.nav-collapse -->
        </div>
      </div>
      <!-- /navbar-inner -->
    </div>
    <!-- /navbar -->

app/views/layouts/_sidebar.html.erb
 <div class="sidebar">
      <ul class="widget widget-menu unstyled">
      <!--
      <li class="active"><a href="index.html"><i class="menu-icon icon-dashboard"></i>Dashboard
        </a>
      </li>
      
      <li><a href="activity.html"><i class="menu-icon icon-bullhorn"></i> Employee List </a>
      </li>-->
      <li><%= link_to '<i class="menu-icon icon-dashboard"></i> Dashboard'.html_safe, home_index_path %></li>
    
      <li><%= link_to '<i class="menu-icon icon-paste"></i> User List'.html_safe, all_users_home_index_path %></li>

      <li><%= link_to '<i class="menu-icon icon-paste"></i> Leave Configuration'.html_safe, leave_configuration_home_index_path %></li>

      <li><%= link_to '<i class="menu-icon icon-paste"></i> Asset Information'.html_safe, add_assets_home_index_path(id:current_user.id) %></li>
      <!--
      <li><%= link_to '<i class="menu-icon icon-paste"></i> Add Employee'.html_safe, add_employee_home_index_path %></li>

      <li><%= link_to '<i class="menu-icon icon-paste"></i> Employee List'.html_safe, employee_list_home_index_path %></li>

      
      

      
      <li><a href="message.html"><i class="menu-icon icon-inbox"></i>Inbox <b class="label green pull-right">
        11</b> </a>
      </li>
      <li><a href="task.html"><i class="menu-icon icon-tasks"></i>Tasks <b class="label orange pull-right">
        19</b> </a>
      </li>
    </ul>
    </.widget-nav>
    <ul class="widget widget-menu unstyled">
      <li><a href="ui-button-icon.html"><i class="menu-icon icon-bold"></i> Buttons </a></li>
      <li><a href="ui-typography.html"><i class="menu-icon icon-book"></i>Typography </a></li>
      <li><a href="table.html"><i class="menu-icon icon-table"></i>Tables </a></li>
      <li><a href="charts.html"><i class="menu-icon icon-bar-chart"></i>Charts </a></li>
    </ul>
    </.widget-nav>
    <ul class="widget widget-menu unstyled">
      <li>
        <a class="collapsed" data-toggle="collapse" href="#togglePages"><i class="menu-icon icon-cog">
        </i><i class="icon-chevron-down pull-right"></i><i class="icon-chevron-up pull-right">
        </i>More Pages </a>
        <ul id="togglePages" class="collapse unstyled">
          <li><a href="other-login.html"><i class="icon-inbox"></i>Login </a></li>
          <li><a href="other-user-profile.html"><i class="icon-inbox"></i>Profile </a></li>
          <li><a href="other-user-listing.html"><i class="icon-inbox"></i>All Users </a></li>
        </ul>
      </li>
      <li><a href="#"><i class="menu-icon icon-signout"></i>Logout </a></li> --> 
              </ul>
            </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <title>Kumolus</title>
    
    <link rel="icon" type="image/png" href="/assets/logo.jpg">


    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %>  
  </head>
  <%if current_user%>
    <%= render "/layouts/navbar" %>

  <%end%>
  <body>
    <% flash.each do |key, value| %>
       <div class="flash <%= key %>"><%= value %></div>
        
    <% end %>
    <%= yield %>
  </body>
  <%= render "/layouts/footer" %>
</html>